# -*- coding: utf-8 -*-
"""work@home1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w3tDoLbY9prp4A4sh8Je7B_pz6TzAfhw

# **Work@Home1:**Simple Python code to send user message and get Gemini response

## Install Required Package
"""

#!pip install -q google-generativeai

"""## Import and Configure Gemini API"""

import google.generativeai as genai
#from google.colab import userdata
#key = userdata.get('GOOGLE_API_KEY')

# Set up API Key
genai.configure(api_key = key)

"""## Initialize Gemini Model"""

# Load the Gemini model
model = genai.GenerativeModel("gemini-1.5-pro")

"""## Define Function to Chat with Gemini"""

def chat_with_gemini(user_message):
    response = model.generate_content(user_message)
    return response.text

"""## Get User Input and Print Response"""

# Take user input
user_input = input("Enter your message: ")

# Get Gemini's response
response = chat_with_gemini(user_input)

# Print response
print("Gemini Response:", response)